resources:
  - apiVersion: v1
    kind: Service
    metadata:
      name: maxwell
    spec:
      selector:
        app: maxwell
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: maxwell
    spec:
      serviceName: maxwell
      replicas: 1
      selector:
        matchLabels:
          app: maxwell
      template:
        metadata:
          labels:
            app: maxwell
        spec:
          containers:
          - name: maxwell
            image: zendesk/maxwell:v1.41.0
            imagePullPolicy: IfNotPresent
            command:
            - bin/maxwell
            args:
            - "--env_config_prefix=MW_"
            - "--config=/usr/local/etc/maxwell/config.properties"
            # - "--ha"
            # - "--raft_member_id=$(POD_NAME)"
            # env:
            # - name: POD_NAME
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.name
            volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/maxwell
            envFrom:
            - configMapRef:
                name: maxwell-env
            ports:
              - name: maxwell
                containerPort: 8080
                protocol: TCP
            livenessProbe:
              httpGet:
                path: /diagnostic
                port: 8080
              initialDelaySeconds: 20
              periodSeconds: 2
          volumes:
          - name: config-volume
            configMap:
              name: maxwell-configmap
              items:
                - key: config.properties
                  path: config.properties
                # - key: maxwell.raft.xml
                #   path: raft.xml
      volumeClaimTemplates: []
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: maxwell-configmap
    data:
      config.properties: |
          metrics_type=http
          metrics_jvm=true
          http_port=8080
          http_diagnostic=true
          binlog_heartbeat=true
          http_config=true
          jgroups_config=/usr/local/etc/maxwell/raft.xml
      # maxwell.raft.xml: |
      #   <?xml version='1.0' encoding='utf-8'?>
      #   <config xmlns="urn:org:jgroups"
      #           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      #           xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
      #       <TCP  bind_port="8080" />
      #       <TCPPING async_discovery="true"
      #         initial_hosts="maxwell-1.maxwell,maxwell-2.maxwell,maxwell-3.maxwell"
      #         port_range="3"/>
      #       <PING />
      #       <MERGE3 />
      #       <FD_SOCK/>
      #       <FD_ALL/>
      #       <VERIFY_SUSPECT timeout="1500"/>
      #       <pbcast.NAKACK2 xmit_interval="500" use_mcast_xmit="false"/>
      #       <UNICAST3 xmit_interval="500"/>
      #       <pbcast.STABLE desired_avg_gossip="50000" max_bytes="4M"/>
      #       <raft.NO_DUPES/>
      #       <pbcast.GMS print_local_addr="true" join_timeout="2000"/>
      #       <UFC max_credits="2M" min_threshold="0.4"/>
      #       <MFC max_credits="2M" min_threshold="0.4"/>
      #       <FRAG2 frag_size="60K"/>
      #       <raft.ELECTION election_min_interval="500" election_max_interval="1000" heartbeat_interval="250"/>
      #       <raft.RAFT members="maxwell-0,maxwell-1,maxwell-2" raft_id="${raft_id:undefined}"/>
      #       <raft.REDIRECT/>
      #   </config>
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: maxwell-env
    data:
      MW_HOST: 192.168.122.1
      MW_USER: root
      MW_PASSWORD: "123"
      MW_LOG_LEVEL: info
      MW_PRODUCER: stdout
  - apiVersion: policy/v1
    kind: PodDisruptionBudget
    metadata:
      name: maxwell
    spec:
      minAvailable: 1
      selector:
        matchLabels:
          app: maxwell
